services:
  backend:
    image: eos
    build:
      dockerfile: Dockerfile
      context: ./backend/
    networks:
      - webnet
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./backend/src:/srv/app/src
  postgres:
    container_name: postgres
    image: postgres:17
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    networks:
      - webnet
    depends_on:
      - backend
      - postgres
    expose:
      - 8080
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
networks:
  webnet:
volumes:
  pgdata: